### ISSUE TITLE
Add shift; start/end times cannot have the same value

### ISSUE THREAD

**Issue by sebjimenez** [propedeutica/shift-reservation#18]
- When **adding a new shift** the system should not allow the user to create a shift **starting and ending at the same time**. 

                 Example:
                          Start time: 14:00
                          End time:   14:00
- This should be invalid

![issue5](https://cloud.githubusercontent.com/assets/19265840/18342385/e5b978a4-75ae-11e6-9f03-1e69652fc833.gif)

**Comment by sebjimenez** [comment]
I will look into this issue myself.

**Comment by agarciavera** [comment]
This issue was fixed by PR #19, and it was merge on Sep/09. It can be closed.
