### ISSUE TITLE
Add shift view can display a 'Time Format' hint

### ISSUE THREAD

**Issue by sebjimenez** [propedeutica/shift-reservation#20]
Current view of **add shift doesn't** indicate to the user **the time format** that needs to be followed in order to create a valid shift (hh:mm). If a simple **hint or help line** is added, a lot of users wont need the error messages to write the start/end times properly.

![image](https://cloud.githubusercontent.com/assets/19265840/18341533/aa1cc430-75aa-11e6-962c-53db11ef6cb7.png)

**Comment by sebjimenez** [comment]
These are the two options I propose: 

- Option 1: * Time format -> hh:mm
- Option 2: hh:mm

![image](https://cloud.githubusercontent.com/assets/19265840/18345950/20372d64-75be-11e6-9d57-ed85ff8de94e.png)

**Comment by sergio-ocon** [comment]
Please use patternfly styles:
http://www.patternfly.org/pattern-library/forms-and-controls/forms/#_

**Comment by sergio-ocon** [comment]
A way to select hours could be great too

**Comment by aljesusg** [comment]
Y esto http://www.patternfly.org/pattern-library/forms-and-controls/time-picker/#_code ?

**Comment by sergio-ocon** [comment]
That is really really cool

**Comment by sergio-ocon** [comment]
updated with this form and control, so the user selects it graphically
