### ISSUE TITLE
Add room; capacity should be validated to have a maximum limit

### ISSUE THREAD

**Issue by sebjimenez** [propedeutica/shift-reservation#29]
- When **adding a new room**, the system allows to use **very high values** (not realistic) in the "Capacity" attribute. 
- There should be a **validation** before accepting the addition to prevent the user to enter a value higher than the **Maximum capacity** that the admin can configure. 

![issue8](https://cloud.githubusercontent.com/assets/19265840/18392580/9a420738-76b2-11e6-964e-0749830f0792.gif)

**Comment by sergio-ocon** [comment]
I don't think this issue is valid. Only the administrator can use this, and then it is up to him to create them properly
