### ISSUE TITLE
Add shift; this view should have a 'Go Back' button

### ISSUE THREAD

**Issue by sebjimenez** [propedeutica/shift-reservation#30]
- In the **Add shift** view there is no option for the user to **Go Back** to the Room_Index using a **button**. Only using the main menu-bar. There should be a button in this view.

- Also 'add shift' button is **not** capitalized

![image](https://cloud.githubusercontent.com/assets/19265840/18392945/fabb24b8-76b3-11e6-9ecf-a7cbfd724b3a.png)

**Comment by sebjimenez** [comment]
I will work on this issue myself

**Comment by sergio-ocon** [comment]
These is a bug + one enhancement.... IT is small enough to go through, but please next time split it in two.

**Comment by sergio-ocon** [comment]
Didn't you do this already, @sebjimenez ?
