### ISSUE TITLE
Rspec doesn't work

### ISSUE THREAD

**Issue by agarciavera** [propedeutica/shift-reservation#47]
![screenshot from 2016-09-16 19-30-36](https://cloud.githubusercontent.com/assets/19265820/18595932/2f26cd7c-7c47-11e6-9387-978a9304afa4.png)

**Comment by sergio-ocon** [comment]
You need to provide information:
Master is working (you can see travis).
What is your bundle and bundle.lock file
bundle list
bower list

**Comment by sergio-ocon** [comment]
Fixed
